from __future__ import annotations

import os

APP_NAME = "research_agent"
APP_VERSION = "0.2.0"

ENV_FILE = ".env"
ENV_FILE_ENCODING = "utf-8"
DEFAULT_ENVIRONMENT = "development"

DEFAULT_LOG_LEVEL = "INFO"
VALID_LOG_LEVELS = {"CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"}

DEFAULT_OUTPUT_DIR = "output"
DEFAULT_CACHE_DIR = "cache"
DEFAULT_DATA_DIR = "data"
DEFAULT_LOGS_DIR = "logs"

OUTPUT_JSON_DIR = "json"
OUTPUT_MARKDOWN_DIR = "markdown"
OUTPUT_REPORTS_DIR = "reports"
DATA_RAW_DIR = "raw"
DATA_PROCESSED_DIR = "processed"

_USER_AGENT_CONTACT = os.getenv("RESEARCH_AGENT_CONTACT", "").strip()
if _USER_AGENT_CONTACT:
    USER_AGENT = (
        f"{APP_NAME}/{APP_VERSION} "
        f"(personal research agent; educational use; "
        f"contact: {_USER_AGENT_CONTACT})"
    )
else:
    USER_AGENT = (
        f"{APP_NAME}/{APP_VERSION} "
        f"(personal research agent; educational use)"
    )

DEFAULT_HEADERS = {
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "User-Agent": USER_AGENT,
}

PROVIDER_SAMBANOVA = "SAMBANOVA"
PROVIDER_GROQ = "GROQ"
PROVIDER_GOOGLE = "GOOGLE"
PROVIDER_MISTRAL = "MISTRAL"
PROVIDER_NVIDIA = "NVIDIA"

SUPPORTED_LLM_PROVIDERS = (
    PROVIDER_SAMBANOVA,
    PROVIDER_GROQ,
    PROVIDER_GOOGLE,
    PROVIDER_MISTRAL,
    PROVIDER_NVIDIA,
)

ENV_VAR_BY_PROVIDER = {
    PROVIDER_SAMBANOVA: "SAMBANOVA_API_KEY",
    PROVIDER_GROQ: "GROQ_API_KEY",
    PROVIDER_GOOGLE: "GOOGLE_API_KEY",
    PROVIDER_MISTRAL: "MISTRAL_API_KEY",
    PROVIDER_NVIDIA: "NVIDIA_API_KEY",
}

SAMBANOVA_BASE_URL = "https://api.sambanova.ai/v1"
GROQ_BASE_URL = "https://api.groq.com/openai/v1"
GOOGLE_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
MISTRAL_BASE_URL = "https://api.mistral.ai/v1"
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"

PROVIDER_BASE_URLS = {
    PROVIDER_SAMBANOVA: SAMBANOVA_BASE_URL,
    PROVIDER_GROQ: GROQ_BASE_URL,
    PROVIDER_GOOGLE: GOOGLE_BASE_URL,
    PROVIDER_MISTRAL: MISTRAL_BASE_URL,
    PROVIDER_NVIDIA: NVIDIA_BASE_URL,
}

MODELS_ENDPOINT = "/models"
CHAT_COMPLETIONS_ENDPOINT = "/chat/completions"
GOOGLE_GENERATE_ENDPOINT_TEMPLATE = "/models/{model}:generateContent"

ARXIV_BASE_URL = "http://export.arxiv.org/api"
SEMANTIC_SCHOLAR_BASE_URL = "https://api.semanticscholar.org/graph/v1"
OPENALEX_BASE_URL = "https://api.openalex.org"
GITHUB_BASE_URL = "https://api.github.com"
WIKIPEDIA_BASE_URL = "https://en.wikipedia.org/api/rest_v1"
HUGGINGFACE_BASE_URL = "https://huggingface.co/api"
TAVILY_BASE_URL = "https://api.tavily.com"
EXA_BASE_URL = "https://api.exa.ai"
CORE_BASE_URL = "https://api.core.ac.uk/v3"
SERPER_BASE_URL = "https://google.serper.dev"
SERPAPI_BASE_URL = "https://serpapi.com"
JINA_BASE_URL = "https://r.jina.ai"
JINA_SEARCH_BASE_URL = "https://s.jina.ai"

DEFAULT_TIMEOUT_SECONDS = 45.0
DEFAULT_CONNECT_TIMEOUT_SECONDS = 10.0
DEFAULT_MAX_RETRIES = 2
DEFAULT_RETRY_BACKOFF_SECONDS = 1.0
DEFAULT_RATE_LIMIT_PER_MINUTE = 10

DEFAULT_TEMPERATURE = 0.0
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.0
DEFAULT_MAX_TOKENS = 2048
MIN_MAX_TOKENS = 1
MAX_MAX_TOKENS = 8192
DEFAULT_TOP_P = 1.0

DEFAULT_CONSENSUS_THRESHOLD = 0.7
MIN_CONSENSUS_THRESHOLD = 0.0
MAX_CONSENSUS_THRESHOLD = 1.0

VOTING_MODE_MAJORITY = "majority"
VOTING_MODE_WEIGHTED = "weighted"
VOTING_MODE_UNANIMOUS = "unanimous"
VOTING_MODE_JUDGE = "judge"

SUPPORTED_VOTING_MODES = (
    VOTING_MODE_MAJORITY,
    VOTING_MODE_WEIGHTED,
    VOTING_MODE_UNANIMOUS,
    VOTING_MODE_JUDGE,
)

DEFAULT_JUDGE_MODEL = "mistral-large-latest"
DEFAULT_PRIMARY_FAST_MODEL = "mistral-small-latest"
DEFAULT_PRIMARY_STRONG_MODEL = "mistral-large-latest"
DEFAULT_FALLBACK_STRONG_1 = "DeepSeek-V3.2"
DEFAULT_FALLBACK_STRONG_2 = "qwen/qwen3.6-27b"
DEFAULT_FALLBACK_STRONG_3 = "Meta-Llama-3.3-70B-Instruct"
DEFAULT_FALLBACK_FAST_1 = "qwen/qwen3.6-27b"
DEFAULT_FALLBACK_FAST_2 = "Meta-Llama-3.3-70B-Instruct"
DEFAULT_FALLBACK_FAST_3 = "mistral-small-latest"
DEFAULT_CODE_MODEL = "codestral-latest"
DEFAULT_EMBEDDING_MODEL = "mistral-embed"

SOURCE_PLATFORM_ARXIV = "arxiv"
SOURCE_PLATFORM_SEMANTIC_SCHOLAR = "semantic_scholar"
SOURCE_PLATFORM_OPENALEX = "openalex"
SOURCE_PLATFORM_GITHUB = "github"
SOURCE_PLATFORM_WIKIPEDIA = "wikipedia"
SOURCE_PLATFORM_HUGGINGFACE = "huggingface"
SOURCE_PLATFORM_WEB = "web"
SOURCE_PLATFORM_TAVILY = "tavily"
SOURCE_PLATFORM_EXA = "exa"
SOURCE_PLATFORM_CORE = "core"
SOURCE_PLATFORM_SERPER = "serper"
SOURCE_PLATFORM_SERPAPI = "serpapi"
SOURCE_PLATFORM_JINA = "jina"

SOURCE_TYPE_PAPER = "research_paper"
SOURCE_TYPE_REPOSITORY = "repository"
SOURCE_TYPE_COURSE = "course"
SOURCE_TYPE_VIDEO = "video"
SOURCE_TYPE_BLOG = "blog"
SOURCE_TYPE_DOCUMENTATION = "documentation"
SOURCE_TYPE_DATASET = "dataset"
SOURCE_TYPE_MODEL = "model"
SOURCE_TYPE_OTHER = "other"

DIFFICULTY_BEGINNER = "beginner"
DIFFICULTY_INTERMEDIATE = "intermediate"
DIFFICULTY_ADVANCED = "advanced"

MIN_SEARCH_QUERY_LENGTH = 2
MAX_SEARCH_QUERY_LENGTH = 500
DEFAULT_MAX_RESULTS = 20
MIN_MAX_RESULTS = 1
MAX_MAX_RESULTS = 100

CACHE_NAMESPACE = APP_NAME
CACHE_DEFAULT_TTL_SECONDS = 86400
CACHE_MAX_ENTRIES = 10000

TEXT_SNIPPET_LENGTH = 500
MAX_LLM_PROMPT_LENGTH = 12000
DEFAULT_SCORE_PRECISION = 4

MIN_RANKING_CONFIDENCE = 0.0
MAX_RANKING_CONFIDENCE = 1.0

AGENT_DEFAULT_MAX_ITERATIONS = 15
AGENT_MIN_MAX_ITERATIONS = 1
AGENT_MAX_MAX_ITERATIONS = 50

AGENT_DEFAULT_TOKEN_BUDGET = 40000
AGENT_MIN_TOKEN_BUDGET = 1000
AGENT_MAX_TOKEN_BUDGET = 500000

AGENT_DEFAULT_QUALITY_THRESHOLD = 0.7
AGENT_MIN_QUALITY_THRESHOLD = 0.0
AGENT_MAX_QUALITY_THRESHOLD = 1.0

AGENT_DEFAULT_MAX_RETRIES_PER_STEP = 2
AGENT_MIN_RETRIES_PER_STEP = 0
AGENT_MAX_RETRIES_PER_STEP = 5

AGENT_WRAP_UP_THRESHOLD_PERCENT = 85.0
AGENT_CRITICAL_THRESHOLD_PERCENT = 95.0
AGENT_WRAP_UP_MODE_BUDGET = 3000

AGENT_PLANNING_BUDGET = 5000
AGENT_SEARCH_BUDGET = 3000
AGENT_READING_BUDGET = 15000
AGENT_RANKING_BUDGET = 8000
AGENT_SUMMARIZATION_BUDGET = 6000
AGENT_REFLECTION_BUDGET = 3000
AGENT_SYNTHESIS_BUDGET = 5000

AGENT_MEMORY_TYPE_EPISODIC = "episodic"
AGENT_MEMORY_TYPE_SEMANTIC = "semantic"
AGENT_MEMORY_TYPE_PROCEDURAL = "procedural"

AGENT_EVENT_STARTED = "agent.started"
AGENT_EVENT_PLANNING = "agent.planning"
AGENT_EVENT_PLAN_CREATED = "agent.plan_created"
AGENT_EVENT_THINKING = "agent.thinking"
AGENT_EVENT_ACTING = "agent.acting"
AGENT_EVENT_TOOL_CALLED = "agent.tool_called"
AGENT_EVENT_OBSERVING = "agent.observing"
AGENT_EVENT_REFLECTING = "agent.reflecting"
AGENT_EVENT_REFLECTION_COMPLETED = "agent.reflection_completed"
AGENT_EVENT_STEP_COMPLETED = "agent.step_completed"
AGENT_EVENT_BUDGET_WARNING = "agent.budget_warning"
AGENT_EVENT_BUDGET_EXHAUSTED = "agent.budget_exhausted"
AGENT_EVENT_SYNTHESIZING = "agent.synthesizing"
AGENT_EVENT_COMPLETED = "agent.completed"
AGENT_EVENT_FAILED = "agent.failed"

AGENT_TOKEN_CATEGORY_PLANNING = "planning"
AGENT_TOKEN_CATEGORY_SEARCH = "search"
AGENT_TOKEN_CATEGORY_READING = "reading"
AGENT_TOKEN_CATEGORY_RANKING = "ranking"
AGENT_TOKEN_CATEGORY_SUMMARIZATION = "summarization"
AGENT_TOKEN_CATEGORY_REFLECTION = "reflection"
AGENT_TOKEN_CATEGORY_SYNTHESIS = "synthesis"
AGENT_TOKEN_CATEGORY_MEMORY = "memory"
AGENT_TOKEN_CATEGORY_TOOL_USE = "tool_use"

AGENT_TOOL_SEARCH_ACADEMIC = "search_academic"
AGENT_TOOL_SEARCH_WEB = "search_web"
AGENT_TOOL_SEARCH_GITHUB = "search_github"
AGENT_TOOL_READ_URL = "read_url"
AGENT_TOOL_READ_PAPER = "read_paper"
AGENT_TOOL_RANK_SOURCES = "rank_sources"
AGENT_TOOL_CLASSIFY_DIFFICULTY = "classify_difficulty"
AGENT_TOOL_SUMMARIZE_SOURCE = "summarize_source"
AGENT_TOOL_BUILD_LEARNING_PATH = "build_learning_path"
AGENT_TOOL_ENHANCE_PATH = "enhance_path"
AGENT_TOOL_SAVE_MEMORY = "save_memory"
AGENT_TOOL_RECALL_MEMORY = "recall_memory"
AGENT_TOOL_COMPARE_SOURCES = "compare_sources"