from __future__ import annotations

import os

APP_NAME = "research_agent"
APP_VERSION = "0.2.0"

ENV_FILE = ".env"
ENV_FILE_ENCODING = "utf-8"
DEFAULT_ENVIRONMENT = "development"

DEFAULT_LOG_LEVEL = "INFO"
VALID_LOG_LEVELS = {"CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"}

DEFAULT_OUTPUT_DIR = "output"
DEFAULT_CACHE_DIR = "cache"
DEFAULT_DATA_DIR = "data"
DEFAULT_LOGS_DIR = "logs"

OUTPUT_JSON_DIR = "json"
OUTPUT_MARKDOWN_DIR = "markdown"
OUTPUT_REPORTS_DIR = "reports"
DATA_RAW_DIR = "raw"
DATA_PROCESSED_DIR = "processed"

_USER_AGENT_CONTACT = os.getenv("RESEARCH_AGENT_CONTACT", "").strip()

if _USER_AGENT_CONTACT:
    USER_AGENT = (
        f"{APP_NAME}/{APP_VERSION} "
        f"(personal research agent; educational use; "
        f"contact: {_USER_AGENT_CONTACT})"
    )
else:
    USER_AGENT = (
        f"{APP_NAME}/{APP_VERSION} "
        f"(personal research agent; educational use)"
    )

DEFAULT_HEADERS = {
    "Accept": "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "User-Agent": USER_AGENT,
}

PROVIDER_SAMBANOVA = "SAMBANOVA"
PROVIDER_GROQ = "GROQ"
PROVIDER_GOOGLE = "GOOGLE"
PROVIDER_MISTRAL = "MISTRAL"
PROVIDER_NVIDIA = "NVIDIA"

SUPPORTED_LLM_PROVIDERS = (
    PROVIDER_SAMBANOVA,
    PROVIDER_GROQ,
    PROVIDER_GOOGLE,
    PROVIDER_MISTRAL,
    PROVIDER_NVIDIA,
)

ENV_VAR_BY_PROVIDER = {
    PROVIDER_SAMBANOVA: "SAMBANOVA_API_KEY",
    PROVIDER_GROQ: "GROQ_API_KEY",
    PROVIDER_GOOGLE: "GOOGLE_API_KEY",
    PROVIDER_MISTRAL: "MISTRAL_API_KEY",
    PROVIDER_NVIDIA: "NVIDIA_API_KEY",
}

SAMBANOVA_BASE_URL = "https://api.sambanova.ai/v1"
GROQ_BASE_URL = "https://api.groq.com/openai/v1"
GOOGLE_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
MISTRAL_BASE_URL = "https://api.mistral.ai/v1"
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"

PROVIDER_BASE_URLS = {
    PROVIDER_SAMBANOVA: SAMBANOVA_BASE_URL,
    PROVIDER_GROQ: GROQ_BASE_URL,
    PROVIDER_GOOGLE: GOOGLE_BASE_URL,
    PROVIDER_MISTRAL: MISTRAL_BASE_URL,
    PROVIDER_NVIDIA: NVIDIA_BASE_URL,
}

MODELS_ENDPOINT = "/models"
CHAT_COMPLETIONS_ENDPOINT = "/chat/completions"
GOOGLE_GENERATE_ENDPOINT_TEMPLATE = "/models/{model}:generateContent"

ARXIV_BASE_URL = "http://export.arxiv.org/api"
SEMANTIC_SCHOLAR_BASE_URL = "https://api.semanticscholar.org/graph/v1"
OPENALEX_BASE_URL = "https://api.openalex.org"
GITHUB_BASE_URL = "https://api.github.com"
WIKIPEDIA_BASE_URL = "https://en.wikipedia.org/api/rest_v1"
HUGGINGFACE_BASE_URL = "https://huggingface.co/api"
TAVILY_BASE_URL = "https://api.tavily.com"
EXA_BASE_URL = "https://api.exa.ai"
CORE_BASE_URL = "https://api.core.ac.uk/v3"
SERPER_BASE_URL = "https://google.serper.dev"
SERPAPI_BASE_URL = "https://serpapi.com"
JINA_BASE_URL = "https://r.jina.ai"
JINA_SEARCH_BASE_URL = "https://s.jina.ai"

CROSSREF_BASE_URL = "https://api.crossref.org"
EUROPE_PMC_BASE_URL = "https://www.ebi.ac.uk/europepmc/webservices/rest"
PUBMED_BASE_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
DOAJ_BASE_URL = "https://doaj.org/api"
ZENODO_BASE_URL = "https://zenodo.org/api"
DATACITE_BASE_URL = "https://api.datacite.org"
OPEN_LIBRARY_BASE_URL = "https://openlibrary.org"
INTERNET_ARCHIVE_BASE_URL = "https://archive.org"
WIKIBOOKS_BASE_URL = "https://en.wikibooks.org/w/api.php"
WIKIVERSITY_BASE_URL = "https://en.wikiversity.org/w/api.php"
STACK_EXCHANGE_BASE_URL = "https://api.stackexchange.com/2.3"
HACKER_NEWS_BASE_URL = "https://hn.algolia.com/api/v1"

DEFAULT_TIMEOUT_SECONDS = 45.0
DEFAULT_CONNECT_TIMEOUT_SECONDS = 10.0
DEFAULT_MAX_RETRIES = 2
DEFAULT_RETRY_BACKOFF_SECONDS = 1.0
DEFAULT_RATE_LIMIT_PER_MINUTE = 10

DEFAULT_TEMPERATURE = 0.0
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.0
DEFAULT_MAX_TOKENS = 2048
MIN_MAX_TOKENS = 1
MAX_MAX_TOKENS = 8192
DEFAULT_TOP_P = 1.0

DEFAULT_CONSENSUS_THRESHOLD = 0.7
MIN_CONSENSUS_THRESHOLD = 0.0
MAX_CONSENSUS_THRESHOLD = 1.0

VOTING_MODE_MAJORITY = "majority"
VOTING_MODE_WEIGHTED = "weighted"
VOTING_MODE_UNANIMOUS = "unanimous"
VOTING_MODE_JUDGE = "judge"

SUPPORTED_VOTING_MODES = (
    VOTING_MODE_MAJORITY,
    VOTING_MODE_WEIGHTED,
    VOTING_MODE_UNANIMOUS,
    VOTING_MODE_JUDGE,
)

DEFAULT_JUDGE_MODEL = "mistral-large-latest"
DEFAULT_PRIMARY_FAST_MODEL = "mistral-small-latest"
DEFAULT_PRIMARY_STRONG_MODEL = "mistral-large-latest"
DEFAULT_FALLBACK_STRONG_1 = "DeepSeek-V3.2"
DEFAULT_FALLBACK_STRONG_2 = "qwen/qwen3.6-27b"
DEFAULT_FALLBACK_STRONG_3 = "Meta-Llama-3.3-70B-Instruct"
DEFAULT_FALLBACK_FAST_1 = "qwen/qwen3.6-27b"
DEFAULT_FALLBACK_FAST_2 = "Meta-Llama-3.3-70B-Instruct"
DEFAULT_FALLBACK_FAST_3 = "mistral-small-latest"
DEFAULT_CODE_MODEL = "codestral-latest"
DEFAULT_EMBEDDING_MODEL = "mistral-embed"

SOURCE_PLATFORM_ARXIV = "arxiv"
SOURCE_PLATFORM_SEMANTIC_SCHOLAR = "semantic_scholar"
SOURCE_PLATFORM_OPENALEX = "openalex"
SOURCE_PLATFORM_GITHUB = "github"
SOURCE_PLATFORM_WIKIPEDIA = "wikipedia"
SOURCE_PLATFORM_HUGGINGFACE = "huggingface"
SOURCE_PLATFORM_WEB = "web"
SOURCE_PLATFORM_TAVILY = "tavily"
SOURCE_PLATFORM_EXA = "exa"
SOURCE_PLATFORM_CORE = "core"
SOURCE_PLATFORM_SERPER = "serper"
SOURCE_PLATFORM_SERPAPI = "serpapi"
SOURCE_PLATFORM_JINA = "jina"
SOURCE_PLATFORM_CROSSREF = "crossref"
SOURCE_PLATFORM_EUROPE_PMC = "europe_pmc"
SOURCE_PLATFORM_PUBMED = "pubmed"
SOURCE_PLATFORM_DOAJ = "doaj"
SOURCE_PLATFORM_ZENODO = "zenodo"
SOURCE_PLATFORM_DATACITE = "datacite"
SOURCE_PLATFORM_OPEN_LIBRARY = "open_library"
SOURCE_PLATFORM_INTERNET_ARCHIVE = "internet_archive"
SOURCE_PLATFORM_WIKIBOOKS = "wikibooks"
SOURCE_PLATFORM_WIKIVERSITY = "wikiversity"
SOURCE_PLATFORM_OPENSTAX = "openstax"
SOURCE_PLATFORM_MIT_OCW = "mit_ocw"
SOURCE_PLATFORM_LIBRETEXTS = "libretexts"
SOURCE_PLATFORM_STACK_EXCHANGE = "stack_exchange"
SOURCE_PLATFORM_HACKER_NEWS = "hacker_news"

SOURCE_TYPE_PAPER = "research_paper"
SOURCE_TYPE_REPOSITORY = "repository"
SOURCE_TYPE_COURSE = "course"
SOURCE_TYPE_VIDEO = "video"
SOURCE_TYPE_BLOG = "blog"
SOURCE_TYPE_DOCUMENTATION = "documentation"
SOURCE_TYPE_DATASET = "dataset"
SOURCE_TYPE_MODEL = "model"
SOURCE_TYPE_BOOK = "book"
SOURCE_TYPE_OTHER = "other"

DIFFICULTY_BEGINNER = "beginner"
DIFFICULTY_INTERMEDIATE = "intermediate"
DIFFICULTY_ADVANCED = "advanced"

LEVEL_PROFILE_BEGINNER = "beginner"
LEVEL_PROFILE_MIXED = "mixed"
LEVEL_PROFILE_ADVANCED = "advanced"
LEVEL_PROFILE_BALANCED = "balanced"

VALID_LEVEL_PROFILES = (
    LEVEL_PROFILE_BEGINNER,
    LEVEL_PROFILE_MIXED,
    LEVEL_PROFILE_ADVANCED,
    LEVEL_PROFILE_BALANCED,
)

PLATFORM_TIER_BEGINNER = "beginner"
PLATFORM_TIER_RESEARCH = "research"
PLATFORM_TIER_CODE = "code"
PLATFORM_TIER_REFERENCE = "reference"
PLATFORM_TIER_WEB = "web"

VALID_PLATFORM_TIERS = (
    PLATFORM_TIER_BEGINNER,
    PLATFORM_TIER_RESEARCH,
    PLATFORM_TIER_CODE,
    PLATFORM_TIER_REFERENCE,
    PLATFORM_TIER_WEB,
)

PLATFORM_LEVEL_AFFINITY_BEGINNER = "beginner"
PLATFORM_LEVEL_AFFINITY_INTERMEDIATE = "intermediate"
PLATFORM_LEVEL_AFFINITY_ADVANCED = "advanced"
PLATFORM_LEVEL_AFFINITY_ANY = "any"

VALID_PLATFORM_LEVEL_AFFINITIES = (
    PLATFORM_LEVEL_AFFINITY_BEGINNER,
    PLATFORM_LEVEL_AFFINITY_INTERMEDIATE,
    PLATFORM_LEVEL_AFFINITY_ADVANCED,
    PLATFORM_LEVEL_AFFINITY_ANY,
)

MIN_SEARCH_QUERY_LENGTH = 2
MAX_SEARCH_QUERY_LENGTH = 500
DEFAULT_MAX_RESULTS = 20
MIN_MAX_RESULTS = 1
MAX_MAX_RESULTS = 100

CACHE_NAMESPACE = APP_NAME
CACHE_DEFAULT_TTL_SECONDS = 86400
CACHE_MAX_ENTRIES = 10000

TEXT_SNIPPET_LENGTH = 500
MAX_LLM_PROMPT_LENGTH = 12000
DEFAULT_SCORE_PRECISION = 4

MIN_RANKING_CONFIDENCE = 0.0
MAX_RANKING_CONFIDENCE = 1.0

AGENT_DEFAULT_MAX_ITERATIONS = 15
AGENT_MIN_MAX_ITERATIONS = 1
AGENT_MAX_MAX_ITERATIONS = 50

AGENT_DEFAULT_TOKEN_BUDGET = 40000
AGENT_MIN_TOKEN_BUDGET = 1000
AGENT_MAX_TOKEN_BUDGET = 500000

AGENT_DEFAULT_QUALITY_THRESHOLD = 0.7
AGENT_MIN_QUALITY_THRESHOLD = 0.0
AGENT_MAX_QUALITY_THRESHOLD = 1.0

AGENT_DEFAULT_MAX_RETRIES_PER_STEP = 2
AGENT_MIN_RETRIES_PER_STEP = 0
AGENT_MAX_RETRIES_PER_STEP = 5

AGENT_WRAP_UP_THRESHOLD_PERCENT = 85.0
AGENT_CRITICAL_THRESHOLD_PERCENT = 95.0

AGENT_PLANNING_BUDGET = 5000
AGENT_SEARCH_BUDGET = 3000
AGENT_READING_BUDGET = 15000
AGENT_RANKING_BUDGET = 8000
AGENT_SUMMARIZATION_BUDGET = 6000
AGENT_REFLECTION_BUDGET = 3000
AGENT_SYNTHESIS_BUDGET = 5000

AGENT_MEMORY_TYPE_EPISODIC = "episodic"
AGENT_MEMORY_TYPE_SEMANTIC = "semantic"
AGENT_MEMORY_TYPE_PROCEDURAL = "procedural"

AGENT_EVENT_STARTED = "agent.started"
AGENT_EVENT_PLANNING = "agent.planning"
AGENT_EVENT_PLAN_CREATED = "agent.plan_created"
AGENT_EVENT_THINKING = "agent.thinking"
AGENT_EVENT_ACTING = "agent.acting"
AGENT_EVENT_TOOL_CALLED = "agent.tool_called"
AGENT_EVENT_OBSERVING = "agent.observing"
AGENT_EVENT_REFLECTING = "agent.reflecting"
AGENT_EVENT_REFLECTION_COMPLETED = "agent.reflection_completed"
AGENT_EVENT_STEP_COMPLETED = "agent.step_completed"
AGENT_EVENT_BUDGET_WARNING = "agent.budget_warning"
AGENT_EVENT_BUDGET_EXHAUSTED = "agent.budget_exhausted"
AGENT_EVENT_SYNTHESIZING = "agent.synthesizing"
AGENT_EVENT_COMPLETED = "agent_completed"
AGENT_EVENT_FAILED = "agent.failed"

AGENT_TOKEN_CATEGORY_PLANNING = "planning"
AGENT_TOKEN_CATEGORY_SEARCH = "search"
AGENT_TOKEN_CATEGORY_READING = "reading"
AGENT_TOKEN_CATEGORY_RANKING = "ranking"
AGENT_TOKEN_CATEGORY_SUMMARIZATION = "summarization"
AGENT_TOKEN_CATEGORY_REFLECTION = "reflection"
AGENT_TOKEN_CATEGORY_SYNTHESIS = "synthesis"
AGENT_TOKEN_CATEGORY_MEMORY = "memory"
AGENT_TOKEN_CATEGORY_TOOL_USE = "tool_use"

AGENT_TOOL_SEARCH_ACADEMIC = "search_academic"
AGENT_TOOL_SEARCH_WEB = "search_web"
AGENT_TOOL_SEARCH_GITHUB = "search_github"
AGENT_TOOL_READ_URL = "read_url"
AGENT_TOOL_READ_PAPER = "read_paper"
AGENT_TOOL_RANK_SOURCES = "rank_sources"
AGENT_TOOL_CLASSIFY_DIFFICULTY = "classify_difficulty"
AGENT_TOOL_SUMMARIZE_SOURCE = "summarize_source"
AGENT_TOOL_BUILD_LEARNING_PATH = "build_learning_path"
AGENT_TOOL_ENHANCE_PATH = "enhance_path"
AGENT_TOOL_SAVE_MEMORY = "save_memory"
AGENT_TOOL_RECALL_MEMORY = "recall_memory"
AGENT_TOOL_COMPARE_SOURCES = "compare_sources"

KEYLESS_FALLBACK_ENABLED = True
MIN_SOURCES_BEFORE_FALLBACK = 10

DEFAULT_KEYLESS_FALLBACK_PLATFORMS = (
    "arxiv",
    "semantic_scholar",
    "openalex",
    "crossref",
    "europe_pmc",
    "pubmed",
    "doaj",
    "zenodo",
    "open_library",
    "internet_archive",
    "wikibooks",
    "wikiversity",
    "openstax",
    "mit_ocw",
    "wikipedia",
    "github",
    "huggingface",
)

MODE_FAST = "fast"
MODE_BALANCED = "balanced"
MODE_DEEP = "deep"

VALID_MODES = (
    MODE_FAST,
    MODE_BALANCED,
    MODE_DEEP,
)

DEFAULT_MODE = MODE_BALANCED

SUMMARY_CONCURRENCY_FAST = 3
SUMMARY_CONCURRENCY_BALANCED = 3
SUMMARY_CONCURRENCY_DEEP = 4

SUMMARY_BATCH_PAUSE_FAST = 0.0
SUMMARY_BATCH_PAUSE_BALANCED = 0.4
SUMMARY_BATCH_PAUSE_DEEP = 0.2

MODE_DEFAULTS = {
    MODE_FAST: {
        "iterations": 1,
        "model_tier": "fast",
        "top_n": 10,
        "enhance": "none",
        "budget": 8000,
        "wrap_up_threshold": 2000,
        "min_sources": 5,
        "parallel_stages": True,
        "skip_ranking_llm": True,
        "skip_path_llm": True,
        "search_timeout_seconds": 10.0,
        "summarize_max": 5,
        "summarize_concurrency": SUMMARY_CONCURRENCY_FAST,
        "summarize_batch_pause": SUMMARY_BATCH_PAUSE_FAST,
        "max_query_variants": 2,
        "enable_rag": False,
        "use_llm_expansion": False,
    },
    MODE_BALANCED: {
        "iterations": 2,
        "model_tier": "strong",
        "top_n": 15,
        "enhance": "light",
        "budget": 15000,
        "wrap_up_threshold": 4000,
        "min_sources": 8,
        "parallel_stages": True,
        "skip_ranking_llm": False,
        "skip_path_llm": False,
        "search_timeout_seconds": 12.0,
        "summarize_max": 10,
        "summarize_concurrency": SUMMARY_CONCURRENCY_BALANCED,
        "summarize_batch_pause": SUMMARY_BATCH_PAUSE_BALANCED,
        "max_query_variants": 3,
        "enable_rag": False,
        "use_llm_expansion": True,
    },
    MODE_DEEP: {
        "iterations": 15,
        "model_tier": "strong",
        "top_n": 20,
        "enhance": "full",
        "budget": 40000,
        "wrap_up_threshold": 8000,
        "min_sources": 10,
        "parallel_stages": True,
        "skip_ranking_llm": False,
        "skip_path_llm": False,
        "search_timeout_seconds": 20.0,
        "summarize_max": 20,
        "summarize_concurrency": SUMMARY_CONCURRENCY_DEEP,
        "summarize_batch_pause": SUMMARY_BATCH_PAUSE_DEEP,
        "max_query_variants": 5,
        "enable_rag": True,
        "use_llm_expansion": True,
    },
}

DEFAULT_ACT_TIMEOUT = 30.0
ACT_TIMEOUT_MIN = 5.0
ACT_TIMEOUT_MAX = 120.0

SEARCH_TOOL_TIMEOUT = 40.0
ORCHESTRATOR_TIMEOUT = 25.0
DIRECT_CLIENT_TIMEOUT = 12.0

TOOL_DEFAULT_TIMEOUT = 30.0
TOOL_TIMEOUT_MIN = 5.0
TOOL_TIMEOUT_MAX = 120.0

DEFAULT_THINK_MAX_TOKENS = 500
THINK_TEMPERATURE = 0.0

SUMMARY_MAX_TOKENS = 200
SUMMARY_CONCURRENCY = 3
SUMMARY_BATCH_SIZE = 6
SUMMARY_BATCH_PAUSE = 0.0
SUMMARY_MAX_RETRIES = 2
SUMMARY_RETRY_BACKOFF_SECONDS = 1.5

SUMMARY_CONCURRENCY_FAST = 3
SUMMARY_CONCURRENCY_BALANCED = 3
SUMMARY_CONCURRENCY_DEEP = 4

SUMMARY_BATCH_PAUSE_FAST = 0.0
SUMMARY_BATCH_PAUSE_BALANCED = 0.4
SUMMARY_BATCH_PAUSE_DEEP = 0.2

RANKER_MAX_OUTPUT_TOKENS_FLOOR = 1200
RANKER_MAX_OUTPUT_TOKENS_PER_SOURCE = 80
RANKER_TEMPERATURE = 0.0

PATH_TOKEN_FLOOR = 4000
PATH_TOKEN_CEILING = 6000
PATH_PER_STEP_TOKENS = 600
PATH_WRAPPER_TOKENS = 1500
PATH_TRUNCATION_RATIO = 0.98
PATH_MIN_STEP_RESOURCE_SCORE = 0.30
PATH_MINIMUM_STEPS = 3
PATH_MAX_TARGET_STEPS = 6

ENHANCER_MAX_TOKENS = 800
ENHANCER_TEMPERATURE = 0.0

SEARCH_REQUEST_TIMEOUT = 12.0
SEARCH_CONCURRENCY = 6
SEARCH_MAX_QUERY_VARIANTS = 5

MAX_SOURCES_TO_SUMMARIZE = 20
MAX_SOURCES_TO_RANK = 20

RAG_DEFAULT_ANSWER_STYLE = "standard"
RAG_CHUNK_QUERY_TOKEN_THRESHOLD = 3
RAG_CHUNK_GATE_MIN_TOKENS = 2
RAG_CHUNK_GATE_MAX_TOKENS = 20

EMBEDDING_BATCH_SIZE = 32
EMBEDDING_MAX_RETRIES = 2
EMBEDDING_RETRY_BACKOFF_SECONDS = 1.5

QUALITY_FLOOR_MIN_SCORE = 0.20
QUALITY_FLOOR_MIN_SOURCES = 3
QUALITY_FLOOR_BAND_RATIO = 0.50
RELEVANCE_RETENTION_RATIO = 0.40
RELEVANCE_ABSOLUTE_FLOOR = 0.10
TOPIC_PRESENCE_MIN_OVERLAP = 1
TOPIC_PRESENCE_MIN_COVERAGE = 0.20
BEGINNER_RESCUE_MAX = 2
BEGINNER_RESCUE_MIN_SCORE_RATIO = 0.60
BEGINNER_RESCUE_MIN_RELEVANCE = 0.20