from __future__ import annotations

from typing import Any

from storage.file_manager import FileManager
from utils.text import clean_text, normalize_newlines, truncate_text


def _escape(value: Any) -> str:
    text = clean_text(value) if value is not None else ""
    text = text.replace("|", "\\|")
    text = text.replace("\r", " ")
    text = text.replace("\n", " ")
    text = " ".join(text.split())
    return text


def _escape_link_text(value: Any) -> str:
    text = _escape(value)
    return text.replace("[", "\\[").replace("]", "\\]")


def _safe_url(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    text = text.replace(" ", "%20")
    text = text.replace("|", "%7C")
    text = text.replace("(", "%28")
    text = text.replace(")", "%29")
    return text


def _fmt_float(value: Any) -> str:
    if value is None:
        return "-"
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "-"


def _fmt_latency(value: Any) -> str:
    try:
        ms = float(value)
    except (TypeError, ValueError):
        return "-"
    if ms < 1:
        return "<1 ms"
    if ms < 1000:
        return f"{ms:.0f} ms"
    if ms < 60000:
        return f"{ms / 1000.0:.2f} s"
    minutes = int(ms // 60000)
    seconds = (ms % 60000) / 1000.0
    return f"{minutes}m {seconds:04.1f}s"


def _enum(value: Any) -> str:
    return str(getattr(value, "value", value) or "")


class MarkdownWriter:
    def __init__(self, file_manager: FileManager) -> None:
        self._file_manager = file_manager

    def write(
        self,
        content: str,
        filename: str,
        subdirectory: str = "markdown",
    ) -> Any:
        path = self._file_manager.build_path(
            filename, subdirectory=subdirectory
        )
        return self._file_manager.write_text(
            path, normalize_newlines(content)
        )

    def write_state(
        self,
        state: Any,
        filename: str,
        subdirectory: str = "markdown",
    ) -> Any:
        content = self.render_state(state)
        return self.write(content, filename, subdirectory=subdirectory)

    def render_state(self, state: Any) -> str:
        payload = self._state_to_payload(state)
        return self.render_payload(payload)

    def render_result(self, result: Any) -> str:
        return self.render_state(result)

    def render_payload(self, payload: dict[str, Any]) -> str:
        data = self._normalize(payload)

        lines: list[str] = []
        lines.extend(self._header(data))
        lines.extend(self._overview(data))
        lines.extend(self._funnel(data))
        lines.extend(self._tokens(data))
        lines.extend(self._ranked(data))
        lines.extend(self._summaries(data))
        lines.extend(self._learning_path(data))
        lines.extend(self._platforms(data))
        lines.extend(self._diagnostics(data))
        lines.extend(self._saved_files(data))
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by ATHENA.*")
        lines.append("")

        text = "\n".join(lines)
        while "\n\n\n" in text:
            text = text.replace("\n\n\n", "\n\n")
        return text

    def _state_to_payload(self, state: Any) -> dict[str, Any]:
        try:
            dump = getattr(state, "model_dump", None)
            if callable(dump):
                return dump(mode="json", exclude_none=False, by_alias=False)
        except Exception:
            pass
        return {
            "request_id": getattr(state, "request_id", ""),
            "status": _enum(getattr(state, "status", "")),
            "query": {
                "topic": getattr(getattr(state, "query", None), "topic", ""),
                "goal": getattr(getattr(state, "query", None), "goal", ""),
                "level": getattr(getattr(state, "query", None), "level", ""),
            },
            "ranked_sources": [
                self._model_to_dict(item)
                for item in (getattr(state, "ranked_sources", []) or [])
            ],
            "source_summaries": [
                self._model_to_dict(item)
                for item in (getattr(state, "source_summaries", []) or [])
            ],
            "learning_path": self._model_to_dict(
                getattr(state, "learning_path", None)
            ),
            "errors": list(getattr(state, "errors", []) or []),
            "warnings": list(getattr(state, "warnings", []) or []),
            "saved_files": dict(getattr(state, "saved_files", {}) or {}),
            "latency_ms": getattr(state, "latency_ms", None),
            "rag_documents_indexed": getattr(state, "rag_documents_indexed", 0),
        }

    def _normalize(self, payload: dict[str, Any]) -> dict[str, Any]:
        if not isinstance(payload, dict):
            return {"topic": "Research Report", "status": "unknown"}

        query = payload.get("query") or {}
        if not isinstance(query, dict):
            query = {}

        topic = (
            payload.get("topic")
            or query.get("topic")
            or payload.get("corrected_topic")
            or payload.get("goal")
            or "Research Report"
        )
        goal = payload.get("goal") or query.get("goal") or ""
        level = payload.get("level") or query.get("level") or ""
        request_id = payload.get("request_id") or payload.get("agent_id") or ""
        kind = payload.get("kind") or (
            "agent" if payload.get("agent_id") else "pipeline"
        )

        sources = payload.get("sources") or payload.get("findings") or []
        ranked = payload.get("ranked_sources") or []
        summaries = (
            payload.get("source_summaries")
            or payload.get("summaries")
            or []
        )

        learning_path = payload.get("learning_path")
        enhanced = payload.get("enhanced_learning_path")

        platform_counts: dict[str, int] = {}
        for item in (ranked or sources):
            src = item.get("source") if isinstance(item, dict) else None
            if src is None and isinstance(item, dict):
                src = item
            if not isinstance(src, dict):
                continue
            platform = str(src.get("platform") or "unknown").lower()
            platform_counts[platform] = platform_counts.get(platform, 0) + 1

        return {
            "kind": kind,
            "topic": topic,
            "goal": goal,
            "level": level,
            "request_id": request_id,
            "status": str(payload.get("status") or "unknown").lower(),
            "mode": payload.get("mode") or "",
            "latency_ms": payload.get("latency_ms"),
            "source_count": len(sources),
            "ranked_count": len(ranked),
            "summary_count": len(summaries),
            "learning_step_count": self._count_steps(learning_path),
            "path_resource_count": self._count_resources(learning_path),
            "rag_documents_indexed": int(
                payload.get("rag_documents_indexed") or 0
            ),
            "ranked_sources": ranked,
            "source_summaries": summaries,
            "learning_path": learning_path,
            "enhanced_learning_path": enhanced,
            "errors": list(payload.get("errors") or []),
            "warnings": list(payload.get("warnings") or []),
            "saved_files": dict(payload.get("saved_files") or {}),
            "platform_counts": platform_counts,
            "total_iterations": int(payload.get("total_iterations") or 0),
            "tokens_used": int(payload.get("total_tokens_used") or 0),
            "token_budget": int(payload.get("total_budget") or 0),
            "tokens_remaining": int(payload.get("tokens_remaining") or 0),
            "detected_level": payload.get("detected_level") or "",
            "domain_confidence": payload.get("domain_confidence") or 0.0,
        }

    def _header(self, data: dict[str, Any]) -> list[str]:
        topic = clean_text(data.get("topic") or "Research Report")
        status = str(data.get("status") or "unknown").upper()
        kind = str(data.get("kind") or "pipeline").upper()
        return [
            f"# {topic}",
            "",
            f"> **{kind} REPORT** · **{status}**",
            "",
        ]

    def _overview(self, data: dict[str, Any]) -> list[str]:
        rows: list[tuple[str, str]] = [
            ("Topic", data.get("topic") or "-"),
            ("Goal", data.get("goal") or "-"),
            ("Level", data.get("level") or data.get("detected_level") or "-"),
            ("Status", str(data.get("status") or "-").upper()),
            ("Request ID", data.get("request_id") or "-"),
            ("Duration", _fmt_latency(data.get("latency_ms"))),
            ("Sources", str(data.get("source_count", 0))),
            ("Ranked", str(data.get("ranked_count", 0))),
            ("Summaries", str(data.get("summary_count", 0))),
            ("Learning Steps", str(data.get("learning_step_count", 0))),
            ("RAG Documents", str(data.get("rag_documents_indexed", 0))),
        ]

        if data.get("kind") == "agent":
            rows.append(("Iterations", str(data.get("total_iterations", 0))))
            rows.append(("Tokens Used", str(data.get("tokens_used", 0))))
            rows.append(("Tokens Budget", str(data.get("token_budget", 0))))

        out = ["## Overview", "", "| Field | Value |", "| :---- | :---- |"]
        for label, value in rows:
            out.append(f"| {_escape(label)} | {_escape(value)} |")
        out.append("")
        return out

    def _funnel(self, data: dict[str, Any]) -> list[str]:
        stages = [
            ("Retrieved", int(data.get("source_count", 0) or 0)),
            ("Ranked", int(data.get("ranked_count", 0) or 0)),
            ("Summarized", int(data.get("summary_count", 0) or 0)),
            ("Path used", int(data.get("path_resource_count", 0) or 0)),
        ]
        max_val = max((v for _, v in stages), default=0) or 1

        out = ["## Research Funnel", "", "| Stage | Count | Share |", "| :---- | ----: | ----: |"]
        for label, value in stages:
            share = (value / max_val) * 100.0
            out.append(f"| {_escape(label)} | {value} | {share:.1f}% |")
        out.append("")
        return out

    def _tokens(self, data: dict[str, Any]) -> list[str]:
        budget = int(data.get("token_budget") or 0)
        used = int(data.get("tokens_used") or 0)
        if budget <= 0 and used <= 0:
            return []
        remaining = int(data.get("tokens_remaining") or max(0, budget - used))
        percent = (used / budget) * 100.0 if budget > 0 else 0.0
        return [
            "## Token Economics",
            "",
            "| Field | Value |",
            "| :---- | ----: |",
            f"| Budget | {budget} |",
            f"| Used | {used} |",
            f"| Remaining | {remaining} |",
            f"| Utilization | {percent:.1f}% |",
            "",
        ]

    def _ranked(self, data: dict[str, Any]) -> list[str]:
        ranked = data.get("ranked_sources") or []
        if not ranked:
            return []

        out = [
            "## Ranked Sources",
            "",
            "| # | Title | Platform | Type | Difficulty | Score | Confidence | Year |",
            "| ----: | :---- | :---- | :---- | :---- | ----: | ----: | ----: |",
        ]

        for index, item in enumerate(ranked, start=1):
            if not isinstance(item, dict):
                continue
            src = item.get("source") if isinstance(item.get("source"), dict) else item
            if not isinstance(src, dict):
                continue

            rank = item.get("rank") or index
            title = clean_text(src.get("title") or "Untitled")
            url = _safe_url(src.get("url"))
            platform = str(src.get("platform") or "-").lower()
            stype = str(src.get("source_type") or "-").replace("_", " ")
            difficulty = str(src.get("difficulty") or "unknown").lower()
            score = _fmt_float(item.get("score"))
            confidence = _fmt_float(item.get("confidence"))
            year = src.get("year") or "-"

            title_md = (
                f"[{_escape_link_text(title)}]({url})"
                if url else _escape_link_text(title)
            )

            out.append(
                f"| {rank} | {title_md} | {_escape(platform)} | "
                f"{_escape(stype)} | {_escape(difficulty)} | {score} | "
                f"{confidence} | {_escape(year)} |"
            )

        out.append("")
        return out

    def _summaries(self, data: dict[str, Any]) -> list[str]:
        summaries = data.get("source_summaries") or []
        if not summaries:
            return []

        out = ["## Source Summaries", ""]

        for index, item in enumerate(summaries, start=1):
            if not isinstance(item, dict):
                continue

            title = clean_text(item.get("title") or "Untitled")
            difficulty = str(item.get("difficulty") or "unknown").lower()
            text = clean_text(item.get("summary") or "")
            why = clean_text(item.get("why_useful") or "")
            topics = item.get("key_topics") or []

            out.append(f"### {index}. {title}")
            out.append("")
            out.append(f"*Difficulty:* `{difficulty}`")
            out.append("")

            if text:
                out.append(f"> {text}")
                out.append("")

            if why:
                out.append(f"**Why useful:** {why}")
                out.append("")

            if isinstance(topics, list) and topics:
                chips = ", ".join(f"`{_escape(t)}`" for t in topics[:10])
                out.append(f"**Key topics:** {chips}")
                out.append("")

        return out

    def _learning_path(self, data: dict[str, Any]) -> list[str]:
        path = data.get("learning_path")
        if not isinstance(path, dict):
            return []
        steps = path.get("steps") or []
        if not isinstance(steps, list) or not steps:
            return []

        enhanced = data.get("enhanced_learning_path")
        enh_map: dict[Any, Any] = {}
        if isinstance(enhanced, dict):
            for entry in (enhanced.get("enhancements") or []):
                if isinstance(entry, dict) and entry.get("step") is not None:
                    enh_map[entry["step"]] = entry

        total_minutes = 0
        out = ["## Learning Path", ""]

        for step in steps:
            if not isinstance(step, dict):
                continue
            number = step.get("step") or 0
            title = clean_text(step.get("title") or "")
            objective = clean_text(step.get("objective") or "")
            minutes = int(step.get("estimated_minutes") or 0)
            total_minutes += minutes

            out.append(f"### Step {number} — {title}")
            out.append("")

            if objective and objective != title:
                out.append(f"*{objective}*")
                out.append("")

            if minutes:
                out.append(f"**Estimated time:** {minutes} minutes")
                out.append("")

            enhancement = enh_map.get(number)
            if isinstance(enhancement, dict):
                for label, key in (
                    ("Prerequisites", "prerequisites"),
                    ("Key concepts", "key_concepts"),
                    ("Suggested projects", "suggested_projects"),
                ):
                    vals = enhancement.get(key) or []
                    if not isinstance(vals, list) or not vals:
                        continue
                    out.append(f"**{label}:**")
                    out.append("")
                    for v in vals[:8]:
                        out.append(f"- {clean_text(v)}")
                    out.append("")

            resources = step.get("resources") or []
            if isinstance(resources, list) and resources:
                out.append("**Resources:**")
                out.append("")
                for res in resources:
                    if not isinstance(res, dict):
                        continue
                    src = res.get("source") if isinstance(res.get("source"), dict) else res
                    if not isinstance(src, dict):
                        continue
                    res_title = clean_text(src.get("title") or "Untitled")
                    res_url = _safe_url(src.get("url"))
                    if res_url:
                        out.append(f"- [{_escape_link_text(res_title)}]({res_url})")
                    else:
                        out.append(f"- {_escape_link_text(res_title)}")
                out.append("")

        if total_minutes:
            out.append(f"**Total estimated time:** {total_minutes} minutes")
            out.append("")

        return out

    def _platforms(self, data: dict[str, Any]) -> list[str]:
        counts = data.get("platform_counts") or {}
        if not isinstance(counts, dict) or len(counts) < 2:
            return []

        total = sum(int(v or 0) for v in counts.values()) or 1

        out = [
            "## Platform Distribution",
            "",
            "| Platform | Count | Share |",
            "| :---- | ----: | ----: |",
        ]
        for name, count in sorted(
            counts.items(), key=lambda kv: -int(kv[1] or 0)
        ):
            share = (int(count or 0) / total) * 100.0
            out.append(f"| {_escape(name)} | {int(count or 0)} | {share:.1f}% |")
        out.append("")
        return out

    def _diagnostics(self, data: dict[str, Any]) -> list[str]:
        errors = data.get("errors") or []
        warnings = data.get("warnings") or []
        if not errors and not warnings:
            return []
        out = ["## Diagnostics", ""]
        for err in errors[:20]:
            out.append(f"- **ERROR** · {_escape(err)}")
        for warn in warnings[:20]:
            out.append(f"- **WARN** · {_escape(warn)}")
        out.append("")
        return out

    def _saved_files(self, data: dict[str, Any]) -> list[str]:
        saved = data.get("saved_files") or {}
        if not isinstance(saved, dict) or not saved:
            return []
        out = [
            "## Saved Files",
            "",
            "| Type | Path |",
            "| :---- | :---- |",
        ]
        for key, value in saved.items():
            out.append(f"| {_escape(str(key))} | `{_escape(str(value))}` |")
        out.append("")
        return out

    def _count_steps(self, path: Any) -> int:
        if not isinstance(path, dict):
            return 0
        return len(path.get("steps") or [])

    def _count_resources(self, path: Any) -> int:
        if not isinstance(path, dict):
            return 0
        total = 0
        for step in path.get("steps") or []:
            if isinstance(step, dict):
                total += len(step.get("resources") or [])
        return total

    def _model_to_dict(self, obj: Any) -> Any:
        if obj is None:
            return None
        if isinstance(obj, dict):
            return obj
        dump = getattr(obj, "model_dump", None)
        if callable(dump):
            try:
                return dump(mode="json", exclude_none=False, by_alias=False)
            except Exception:
                pass
        return str(obj)